/glg4debug/glg4param omit_muon_processes  0.0
/glg4debug/glg4param omit_hadronic_processes  0.0

/rat/db/set DETECTOR experiment "jsns2"
/rat/db/set DETECTOR geo_file "jsns2/jsns2.geo"
#/tracking/storeTrajectory 1

/run/initialize

/process/activate Cerenkov

#/vis/open OGLIQt
#/vis/drawVolume

# BEGIN EVENT LOOP
#/rat/proc simpledaq
#/rat/proc prune
#/rat/procset prune "mc.track:opticalphoton"
/rat/proc count
/rat/procset update 100

# Use IO.default_output_filename
/rat/proclast outroot
#END EVENT LOOP

/glg4scint/setQF 1.0

/generator/add combo gun:point
/generator/vtx/set e+ 0 0 0 50.0
#/generator/vtx/set proton 0 0 0 50.0
#/generator/vtx/set neutron 0 0 0 250.0
/generator/pos/set 0 0 0
#/generator/add external external:uniform:"/net/t2srv0008/app/d-Chooz/Software/kpipe/ratpac-kpipe/kdar_muons/./simple_gen_kdar_event default 100 0 |"
#/generator/rate/set 10.0

/run/beamOn 10000
#/run/beamOn 100
